### ISSUE TITLE
sample does not work

### ISSUE THREAD

**Issue by etxemag75** [synrc/sample#1]
I tried this sample, but result is the same as you have it on your own server:
https://sample.n2o.space/app/index.htm

The page is shown exactly as written in index.html or login.html, but the erlang backend is not able to update the DOM with the nitro functions when you click the different buttons (logout, chat, browse).

event(init) ->
    nitro:update(heading, #h2{id=heading, body=Room}).

I assume this sample was fully working at some point, something broke it?

**Comment by 5HT** [comment]
You are using wrong link.
https://sample.n2o.space/index.htm -- This is application instance.

Sample is sample, it may contains bugs, but not in this case. Please specify you finding and reproduce. This style of error reporting is non acceptable.

**Comment by etxemag75** [comment]
Thx, you are right, but when trying this locally:

```
mad app web sample
cd sample
mad dep com pla rep
open https://127.0.0.1:8001/app/index.htm
```

it behaves the same as https://sample.n2o.space/app/index.htm

and open https://127.0.0.1:8001/index.htm does not work at all.

**Comment by 5HT** [comment]
You could setup URL at nginx part of CDN provider. This is not a place for Erlang code. We are in 3-rd millenium, stop producing DHTML, we are living in an era of websockets! :-)

**Comment by 5HT** [comment]
Also, try to stop producing useless tickets. As I said https://github.com/synrc/n2o/issues/327#issuecomment-493435049 we can add n2o_document. But first you need to understand that you don't need it!

**Comment by etxemag75** [comment]
Sorry to write these tickets, your book was very promising, but the existing N2O documentation and examples does not help much and is far from what it is compared to nitrogenproject.com

This ticket is not about n2o_document, but to get the 'sample' example to work on my mac.
Will give this a last chance tomorrow on linux if there is some compatibility issues, otherwise have to wait with N2O until it gets more mature.

**Comment by 5HT** [comment]
Haha, OK! My mature nitrogen friend :-)
It's better to learn how to install certificates on your machine before writing such passages :-)
N2O powers BANKs https://pb.ua/depozit and https://nynja.io and Nitrogen powers NOTHING, except https://nitrogenproject.com and couple admin pages.

I will tell you story how to use Nitrogen in production and lose CPU and memory (and money). We are doing 4000 commits per year for 7 years, dude. I hate Erlang community, average developer blaming for inability to install TLS cert and can't build the library without dependencies. You don't need N2O, go away. You don't even know how to report bugs, zero culture. We don't need such users or they should pay for the pain they bring to open source drivers.

**Comment by 5HT** [comment]
It's better to learn how to install certificates on your machine before writing such passages :-)

**Comment by 5HT** [comment]
N2O powers BANKs https://pb.ua/depozit and Nitrogen powers NOTHING.

**Comment by etxemag75** [comment]
Yes, and that's why I wanted to use N2O ;)
I have already checked this certificate issue, both with Safari that could bypass not valid certs and also by modifying sample.erl and function start(_,_) -> cowboy:start_tls to cowboy:start_clear to use plain HTTP. Will troubleshot this more tomorrow and also check this on linux side.

**Comment by 5HT** [comment]
How many OS do you need to book an issue ?
How many books I should write for you all to understand that Nitrogen is outdated bullshit ?

![Capture](https://user-images.githubusercontent.com/144776/57957207-31921c80-7904-11e9-9df6-b3dac68d11af.PNG)

![photo_2019-05-18_00-27-33](https://user-images.githubusercontent.com/144776/57957211-348d0d00-7904-11e9-86d3-a7d1e31de422.jpg)

![Screenshot_2019-05-18_00-29-11](https://user-images.githubusercontent.com/144776/57957213-35be3a00-7904-11e9-8efa-3c462b96743b.png)

**Comment by 5HT** [comment]
Please, leave.

**Comment by etxemag75** [comment]
The issue was never about nitrogen compability.

Now sample works locally!!!
```
mad app web sample
cd sample
mad dep com pla rep
open https://127.0.0.1:8001/app/index.htm
```

Maybe your change in **n2o_nitro.erl** last night helped :)

Thx anyway

**Comment by 5HT** [comment]
We also have 20 stable tags besides developer's master. If you're filing Issue for master branch you should be developer of n2o.
