### ISSUE TITLE
Sample not working, mnesia error due to the changes in kvs

### ISSUE THREAD

**Issue by mnill** [synrc/sample#3]
Hi!
I'm new in erlang.
I've tried to run this sample, but faced with error:

`=ERROR REPORT==== 4-Oct-2019::19:28:18.008935 ===
    exception: exit
    reason: {aborted,{bad_type,id_seq,[]}}
    stack: [{mnesia,abort,1,
                    [{file,"/usr/local/Cellar/erlang/22.0.7/lib/erlang/lib/mnesia-4.16/src/mnesia.erl"},
                     {line,356}]},
            {index,chat,2,
                   [{file,"/Users/ilya/repo/test2/sample/src/index.erl"},
                    {line,40}]},
            {n2o_nitro,render_ev,4,
                       [{file,"/Users/ilya/repo/test2/sample/deps/n2o/src/protos/n2o_nitro.erl"},
                        {line,70}]},
            {n2o_nitro,html_events,2,
                       [{file,"/Users/ilya/repo/test2/sample/deps/n2o/src/protos/n2o_nitro.erl"},
                        {line,57}]},
            {n2o_nitro,info,3,
                       [{file,"/Users/ilya/repo/test2/sample/deps/n2o/src/protos/n2o_nitro.erl"},
                        {line,27}]},
            {n2o_proto,push,5,
                       [{file,"/Users/ilya/repo/test2/sample/deps/n2o/src/n2o_proto.erl"},
                        {line,15}]},
            {n2o_cowboy2,websocket_handle,2,
                         [{file,"/Users/ilya/repo/test2/sample/deps/n2o/src/ws/n2o_cowboy2.erl"},
                          {line,19}]},
            {cowboy_websocket,handler_call,6,
                              [{file,"/Users/ilya/repo/test2/sample/deps/cowboy/src/cowboy_websocket.erl"},
                               {line,466}]},
            {cowboy_http,loop,2,
                         [{file,"/Users/ilya/repo/test2/sample/deps/cowboy/src/cowboy_http.erl"},
                          {line,218}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]` 

After some research, i've realised it is because of changes in kvs
https://github.com/synrc/kvs/commit/1dce60d950f474ef94c4a8a4e4ef59a1b99e6592
and
https://github.com/synrc/kvs/commit/1dce60d950f474ef94c4a8a4e4ef59a1b99e6592

The hotfix is stick kvs commit to which one was before this changes,
in rebar.config 
`{kvs,    ".*", {git, "git://github.com/synrc/kvs", {ref, "cce44c97231602ac09912302031df523f83996b3"}}}`

How to migrate this sample to the lastes version of kvs i don't known by now :-(

**Comment by 5HT** [comment]
Thanks for reporting! And sorry for confusing, this is definitely one of ours master mistakes. We've fixed it in KVS/master, just perform the `mad up` to update the sources in `deps`.

**Comment by mnill** [comment]
Thank you
